import type { Metadata } from "next";
import "../globals.css"
import Sidebar from "../components/side-bar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <div className=" bg-inherit w-full min-h-screen flex justify-center items-start">
        <Sidebar/>
         <div className=" w-full flex flex-col justify-start items-start">
             {children}
         </div>
      </div>
 
  );
}
