import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryProvider } from "@/providers/react-query-provider";
import Sidebar from "./components/side-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    <ReactQueryProvider >
      <div className="w-full min-h-screen flex justify-center items-start">
          <Sidebar/>
         <div className="w-full flex-grow flex flex-col justify-start items-start">
             {children}
         </div>
      </div>
    </ReactQueryProvider>
      </body>
    </html>
  );
}
